# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x07predict\"&\n\x10PredictorRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\" \n\x0ePredictorReply\x12\x0e\n\x06result\x18\x01 \x01(\t2L\n\tPredictor\x12?\n\x07Predict\x12\x19.predict.PredictorRequest\x1a\x17.predict.PredictorReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTORREQUEST']._serialized_start=26
  _globals['_PREDICTORREQUEST']._serialized_end=64
  _globals['_PREDICTORREPLY']._serialized_start=66
  _globals['_PREDICTORREPLY']._serialized_end=98
  _globals['_PREDICTOR']._serialized_start=100
  _globals['_PREDICTOR']._serialized_end=176
# @@protoc_insertion_point(module_scope)
